docs.md
scss/_adk-cards.scss
scss/_adk-img.scss
scss/_adk-layout.scss
scss/_adk-table.scss

One more time….better styling and evaluating all options in documentation

Restyled hover on cards and more options in docs

---

scss/_adk-table.scss
scss/_adk-type.scss

- Add margin to table headings

Update Table Headings

---

scss/_adk-img.scss

- Remove background color for `.avatar` class in adk-img.scss

Remove background-color for avatar class in adk-img.scss

---

docs.md

Update ActionBar template & add link styles

---

scss/_adk-header.scss
scss/_adk-variables.scss

These changes go along with the tweaks/refactoring to the header in the application repo.
- Disable text selection
- Set styles for scrolling behavior
- Set font sizes
- Use variables for colors
- Bake in some styles that were previously inlined in the template

Refactor Header styles

---

docs.hbs
docs.md

Tiny changes, just centering the body of the doc site

Centered ADK

---

docs.md
scss/_adk-forms.scss

Add icon input fields

---

docs.md
scss/_adk-forms.scss

Fixes bug with icon inputs where :focus border was not blue

---

scss/_adk-buttons.scss
scss/_adk-variables.scss
scss/_settings.scss

- Updates button paddings
- Updates button background colors
- Sets font colors manually
*Preview:*

Update Button Styles

---

docs.md
scss/_adk-img.scss
scss/_adk-modals.scss
scss/_settings.scss

*NOTE*
Right after this is merged, this PR for `architizer-website` should be merged: https://github.com/Architizer/architizer-website/pull/2065
Old: 
New:
New can also let you do this:

Update Modal & Thumbnail Styles

---

scss/_adk-modals.scss

Allows us to use reveal & reveal-overlay for react modal.

Add styles to display React Modal

---

docs.md
scss/_adk-listview.scss
scss/_adk-type.scss
scss/_adk-variables.scss
scss/adk.scss

- Add List View and List Item 
- Add `Pro Badge` example to `docs.md` for easier use.

Mani/dev 5233/list item component

---

docs.md
scss/_adk-listview.scss

- Add optional Header to List View.

Mani/dev 5234/list view component

---

scss/_adk-listview.scss

- Little nudge to the left, for the Header.

DEV-234 Adjust List View Header padding

---

scss/_adk-listview.scss

- Vertically center Header text in List View

DEV-5234 Minor Design QA Work

---

scss/_adk-forms.scss

- Adds `.inactive` class for form text inputs

Add 'inactive' class for form text inputs

---

docs.md
scss/_adk-cards.scss

PR to replace all `PRO` and `verified` badge inline styles with their respective ADK classes in `docs.md`

Replace all PRO and verified badge references in template docs

---

circle.yml

add gulp task to circle config

---

scss/_adk-layout.scss

- Temporarily revert actionbar colors until we release architizer-website changes

Revert actionbar colors temporarily

---

scss/_adk-layout.scss

Turn actionabrs black

---

docs.md
docs/docs.js
scss/_adk-buttons.scss

- Open to feedback on where to add this code, and the way it's written!

Add pills and pill groups

---

scss/_adk-modals.scss

*** NOTE: THIS IS VULNERABLE. Problems with getting dev environment up - making sass changes to `master` to see changes statically ***

Add revealProductMessage class; test

---

README.md
assets/arrow-left.svg
assets/arrow-right.svg
docs.md
scss/_adk-animations.scss
scss/_adk-buttons.scss
scss/_adk-layout.scss
scss/_adk-modals.scss
scss/_adk-react-select.scss
scss/_adk-spacing.scss
scss/_adk-type.scss
scss/_adk-utilities.scss
scss/_adk-variables.scss
scss/adk.scss

-  Generic utilities:
1. Card overlay top and bottom controls
2. Rounded and radius sizes
3. Block display
4. Common positions
5. Full width and full height
6. Common overflows
7. React Select sizes
8. React Select border sizes
9. Auto margin
10. Line heights as font sizes
11. Link underline colors
12. Common mouse cursors
13. Gutter sizes
14. Dark (black), light (white) buttons
15. Sami transparent buttons (...-transparent)
- Overrides:
1. Disable React modal background scrolling
2. React select highlight on select

Add generic utilities and move some overrides
