Architizer/design-kit

scss/_adk-table.scss
This will fix some issues with the responsive table tricks I added a while back:
**Old:**
**New:**
Add a `width="100%"` to the `<th>` attribute that is the primary table item. The table needs to be told to fill the width of its container, and this will accomplish that.
```html
<div class="row expanded">
<table class="hover">
<thead>
<tr>
<th width="140">Brand</th>
<th width="100%">Product Name</th> 
<th>Status</th>
</tr>
</thead>
<tbody>
<tr>
<td><a class="underline">Knoll</a></td>
<td>Pollock Executive Chair</td>
<td>Recommended</td>
</tr>
</tbody>
</table>
</div>
```
=> Fix issues with table wrapping/blocking on medium screen sizes

gulpfile.js
This will fix the CORS Allowed-Origin issues we often experience when pointing to a local Design Kit in development:
_Solution derived from https://github.com/AveVlad/gulp-connect/issues/100#issuecomment-96078162_
=> Fix CORS issue in local development

scss/_adk-layout.scss
We previously added a `margin-bottom` to all `.actionbar` elements in https://github.com/Architizer/design-kit/pull/80
This is causing some breakage on the layout:
This pull request removes this margin.
=> Remove margin-bottom on .actionbar

docs.md, scss/_adk-cards.scss
This is now the result of any `span.badge` inside `div.card`s.
=> Add classes & documentation for card notification badge

docs.md, scss/_adk-cards.scss, scss/_adk-mixins.scss, scss/_adk-table.scss
This pull request introduces a mixin `notification-dot`, similar to the `loading-spinner` mixin, to be applied on `.has-notification-dot` class for various elements.
(See mixin comments for details about usage).
Now, we get:
This is applied as `.card.has-notification-dot`:
This is applied as `table td.has-notification-dot`:
=> Add ".has-notification-dot"

scss/_adk-forms.scss, scss/_settings.scss
This will add the Foundation Abide styles to the `.ng-invalid` classes so they will show up when Angular form validations fail.
=> Add classes for field validation errors

scss/_adk-forms.scss
This adds styles for validation errors to checkbox elements:
This requires an `<input type="checkbox">` followed by a `<label>` element (this follows Foundation's [standard implementation  of checkbox inputs](http://foundation.zurb.com/sites/docs/forms.html#checkboxes-and-radio-buttons)):
```html
<input id="expense" type="checkbox"><label for="expense">Was too expensive</label>
<input id="aesthetic" type="checkbox"><label for="aesthetic">Didn't match the aesthetic that I was looking for </label>
<input id="requirements" type="checkbox"><label for="requirements">Didn't meet my specification requirements</label>
```
=> Add validation error styles for checkboxes

scss/_settings.scss
Ultimately, a typography pass of foundation should override all `rem-calc`d font-sizes to match our scaling system, or (worse, but faster) override `rem-calc`. 
This is to apply our font size to input labels, currently being used on Source.
=> Override label font size with 'small' from the ADK scale

scss/_adk-orbit.scss, scss/_adk-type.scss
This changes a few lines in the orbit styles.
- Pointer cursor on the previous/next buttons
- No more max-height (we are now handling the height of the orbit via image size through imgix)
- Another small fix for links in paragraphs not breaking on line breaks
=> Orbit Styles

docs.md, scss/_adk-colors.scss, scss/_adk-variables.scss, scss/_settings.scss
These changes add utility classes for setting `:hover` colors.
Prefix any of our existing color classes with `hover-` and it will define the hover behavior on that element with that color.
Example:
```html
<div class="bg-extra-light-gray hover-bg-red-50 border-gray hover-border-red">
<a class="gray hover-red">A gray link that turns red on hover inside of a box with an extra-light-gray background that turns red-50 on hover and a gray border that turns red on hover</a>
</div>
```
=> Add color classes for :hover

scss/_adk-forms.scss
This fixes a little snag we previously had with [Inline Labels on Inputs](http://foundation.zurb.com/sites/docs/forms.html#inline-labels-and-buttons)
Old (non-rounded last borders):
New (rounded right borders if last element):
=> Add rounded borders to input groups

scss/_adk-selectize.scss
This changes the selected items in Selectize elements to use the `.secondary-light` styles from our ADK buttons:
*Note: merging this pull request **will change these styles in production** - test with the `?adk=0787d97` development build method first.*
=> Use ".secondary-light" styles for selected items in Selectize

scss/_adk-menu.scss, scss/_adk-tooltip.scss, scss/_settings.scss, scss/adk.scss
This fixes an issue with dropdown panes that prevented us from overriding their background colors with other utility classes:
**Old:**
**Fixed:**
=> Allow .dropdown-pane to be colors other than $white

docs.md
There was just a `</div>` missing - this fixes the docs pages beyond Images (UI / Forms / Tables / Spacing and Scale / Extensions)
=> Fix broken docs pages

scss/_adk-img.scss, scss/_settings.scss
These changes add a style for `.thumbnail.is-hero` for use with our Attachments component:
=> Add styles for "hero image" in thumbnails

scss/_adk-cards.scss
- Remove transition box shadow from card styling to avoid reload flicker from happening for Masonry layouts
Note: needs to be merged before merging the PR for DEV-3707: https://github.com/Architizer/architizer-website/pull/1935
=> Remove transition box shadow from card style to avoid masonry reload flicker

scss/_adk-img.scss
This adds a `.can-hero` class to set initial opacity for a thumbnail to 0.5 when attachments can be set as a hero image:
=> Add class to dim attachment images when non-hero

scss/_adk-fonts.scss
IE renders a dark grey background color behind the magnifying glass icon. (not pictured here)
=> Add transparency to icon background

scss/_adk-header.scss
Fulfills the ADK portion for this ticket: https://architizer.atlassian.net/browse/DEV-4092 
- Replace the header link color (inactive state) with `$light-gray` for better contrast with the active states.
**_Note: Must be merged before this PR: https://github.com/Architizer/application/pull/3074_**
Recording: http://recordit.co/xEJnL3Ibqe
=> Replace header link color with -gray for better active state contrast

scss/_adk-forms.scss, scss/_adk-variables.scss
PR for the Search Creation modal typeahead styling: https://architizer.atlassian.net/browse/DEV-4011
**Note: Must be merged before the frontend portion: https://github.com/Architizer/architizer-website/pull/1987**
- Adds light blue background to the selected dropdown option
- Changes color of `<li>` text element to black
View changes here: 
Chrome: http://recordit.co/pufGXE5D9j
Safari: http://recordit.co/KTrnHds4Ea
Firefox: http://recordit.co/Bcrrgm90zT
IE: http://g.recordit.co/tk0ucTKfaI.gif
Opera/Yandex-friendly as well.
=> Add styles for search creation typeahead dropdown and input

docs.md, docs/docs.js, scss/_adk-forms.scss, scss/_adk-selectize.scss
These changes refactor some of the classes/functionality for minimal fields so that they don't rely on jQuery (or other JavaScript) to manipulate positioning.
These now use the Angular `ng-invalid` or `ng-empty`-type classes to set error state or placeholder positioning on the fields. I did it this way because I'd rather extend our design kit than change the way Angular assigns "error" or "empty" classes. I figured this was safe enough since we don't use these fields outside of Angular forms currently.
I added usage instructions to the documentation.
Just add `.minimal-field` and `.floating-label` classes to the parent div, and be sure the contents are in the following order:
1. Field (input, select, or textarea element)
1. Label (label element with the placeholder/floating label …
=> Refactor minimal fields to use less JavaScript

scss/_adk-forms.scss
Foundation specifies 50px as the default min-height on textareas (in _global.scss from the source files)
(From Foundation's base files):
This is incompatible with our minimal fields and also not necessarily a desired behavior because 50px is arbitrary and doesn't tie to any of the spacing variables we use in Design Kit
These changes overwrite the Foundation default min-height for textareas to use initial values set in other parts of Foundation
=> Fix textarea min-height

scss/_adk-react-select.scss, scss/adk.scss
I'm including the react-select styles directly into the adk.css file because we were having some issues with clashing classes when we included the react-select styles into the page in other ways.
Here's an example of a react-select element in a view in Django:
=> Add react-select styles to adk.css

scss/_adk-modals.scss
Making sure they are not affected by the more general `.header` and `.footer` global styles.
__Before:__
__After:__
=> Add `header` and `footer` styles for Foundation modals

scss/_adk-cards.scss
Lightening the card border to make less heavy handed and also bringing back the hover transition to make it less jarring. We removed the transition when implementing masonry because it was causing some flickering, but I don’t seem to be experiencing that anymore. If masonry cards are working well with this PR then it would be nice! Here’s darrel’s previous commit for ref: 
https://github.com/Architizer/design-kit/commit/ffcd4c30ed5275e0408f7c4e5b1672569e2ba6c5
=> Card transition and styling

scss/_adk-cards.scss
I have a use case where I am displaying inactive cards that aren't clickable - the hover styles were still "lighting up" the card on hover, so I fixed these hover styles to only apply to `.inactive.clickable` cards.
Old:
New:
=> Only set hover rules on .inactive cards when the card is clickable

scss/_settings.scss
Here is the pull request to spread out the breakpoints.
The former `medium`, `large`, and `xlarge` were too close together, so we effectively removed `large` and shifted the others to fill in this gap.
_Just read the diff, you'll get it_
=> Change large breakpoints

scss/_adk-forms.scss
PR to make the `label` color match that of the disabled input text field:
=> Add color property to disabled input text label

scss/_adk-cards.scss
Adding display:block to card class. Image issue still exists with firefox whether using css grid or flex. This shouldn’t affect anything across the board.
=> Add display:block to card class

scss/_adk-cards.scss
Prevents cases where a full-height card, relying on a `display-flex` is collapsing.
=> Move `display:block` rule to only affect cards with `responsive-image class

scss/_adk-listview.scss
I un-nested some of these `.list-view` classes because [getting too specific is bad](https://csswizardry.com/2012/05/keep-your-css-selectors-short/)
This sets me up to use these classes outside of `.list-view` components later
This also prevents breakage in the meantime (because the existing markup in the app will still work) so I can rework the list-view elements in the templates.
=> Reduce specificity of .list-view classes

scss/_settings.scss
This updates the styles used for the Foundation Tabs component
I removed background colors from the tab elements themselves so that they can inherit the background of their parent.
We use these in the Shortlist/Dismissed sidebar on the Products view:
=> Update styles for Tabs

scss/_adk-type.scss
- Adds class to wrap text in quotes. Useful for typeahead guiding text specifically.
=> DEV-5518 Add utility class to surround text in quotes

scss/_adk-dropzone.scss
- Adds `short` class to `dropzone` for design cases like below.
=> Add `short` variant to `dropzone` styles

docs.md, scss/_adk-badges.scss
PR to fix styling of BETA, PRO and Verified badge due to Neue Haas font change:
- Includes removal of unnecessary `.badge` and font-style classes for the BETA badge
PRO: 
BETA:
=> Darell/dev 5589/fix pro beta badge

scss/_adk-layout.scss, scss/_settings.scss
- Create `.light` variation on menus
- Globally makes dropdown more narrow, overriding Foundation base settings
=> Mani/dev 5630/help center

scss/_adk-tags.scss
PR to restore removed light gray border for `.tag` class:
=> Restore light gray border for tags

scss/_adk-tags.scss
PR to align tag text vertically by reducing top padding:
Before:
After:
=> Align tag text vertically by reducing top padding

scss/_adk-layout.scss
These are some updates to link styles in `.actionbar`. I've tested this with old action bars and this shouldn't break any existing link styles
(Brought about by the new updates in DEV-5702)
=> DEV-5702 Updates to Action Bar styles

scss/_adk-layout.scss
This fixes an issue where `.menu` links inside of `.dropdown-pane` were rendering white on hover because we overwrote links inside `.menu`
I want to revise how we approach all of this when we implement this piece in styled-components, but for now, this should satisfy our needs.
=> Fix hover colors on menu links in action bar

scss/_adk-modals.scss
the default was `scroll`, which resulted in unwanted vertical scroll bars.
=> Modals - Set reveal default overflow as auto
